<?php
$oai_url   = FreshRSS_Context::$user_conf->oai_url   ?: 'https://api.openai.com';
$oai_key = FreshRSS_Context::$user_conf->oai_key;
$oai_model = FreshRSS_Context::$user_conf->oai_model ?: 'gpt-5-nano';
$oai_tts_model = FreshRSS_Context::$user_conf->oai_tts_model ?: 'gpt-tts-1';
$oai_voice = FreshRSS_Context::$user_conf->oai_voice ?: 'alloy';
$oai_speed = FreshRSS_Context::$user_conf->oai_speed ?: 1.1;
$oai_prompt = FreshRSS_Context::$user_conf->oai_prompt;
$oai_prompt_2 = FreshRSS_Context::$user_conf->oai_prompt_2;
$oai_provider = FreshRSS_Context::$user_conf->oai_provider ?: 'openai'; // Default to OpenAI
?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
  <input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
  <label for="oai_provider">Choose AI Provider</label>
  <select name="oai_provider">
      <option value="openai" <?php echo ($oai_provider == 'openai' ? 'selected' : ''); ?>>OpenAI</option>
      <option value="ollama" <?php echo ($oai_provider == 'ollama' ? 'selected' : ''); ?>>Ollama</option>
   </select>
 
 <div id="common_config">
    <label for="oai_url">Base URL (http(s)://oai.com/) without 'v1'</label>
    <input type="text" name="oai_url" id="oai_url" value="<?php echo $oai_url; ?>">
    <label for="oai_key">API Key</label>
    <input type="text" name="oai_key" id="oai_key" value="<?php echo $oai_key; ?>">
    <label for="oai_model">Model Name</label>
    <input type="text" name="oai_model" id="oai_model" value="<?php echo $oai_model; ?>">
    <label for="oai_voice">Voix</label>
    <input type="text" name="oai_voice" id="oai_voice" value="<?php echo $oai_voice; ?>">
    <label for="oai_speed">Vitesse de lecture</label>
    <input type="number" name="oai_speed" id="oai_speed" min="0.5" max="4" step="0.1" value="<?php echo $oai_speed; ?>">
    <label for="oai_tts_model">Modèle TTS</label>
    <input type="text" name="oai_tts_model" id="oai_tts_model" value="<?php echo $oai_tts_model; ?>">
    <label for="oai_prompt">Prompt (add before content)</label>
    <textarea name="oai_prompt" id="oai_prompt"><?php echo $oai_prompt; ?></textarea>
    <label for="oai_prompt_2">Second prompt (longer summary)</label>
    <textarea name="oai_prompt_2" id="oai_prompt_2"><?php echo $oai_prompt_2; ?></textarea>
  </div>
  <hr />
  <button type="submit">Save</button>
</form>
